apiVersion: apps/v1
kind: Deployment
metadata:
  name: b18-backend-app
  labels:
    app: b18-backend-app
spec:
  selector:
    matchLabels:
      app: b18-backend-app
  replicas: 2
  template:
    metadata:
      labels:
        app: b18-backend-app
    spec:
      containers:
        - name: b18-backend-app
          image: shubhamkalsait1/b18-backend:latest
          ports:
            - containerPort: 8080